<?php

namespace App\Controller;


use App\Entity\Comment;
use App\Entity\State;
use App\Entity\Traobject;
use App\Form\TraobjectType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class TraobjectController
 * @package App\Controller
 * @Route("/traobject")
 */
class TraobjectController extends BaseController
{
    /**
     * @param Traobject $traobject
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/show/{id}", name="traobject_show")
     */
    public function show(Traobject $traobject)
    {
        $comments = $this->getDoctrine()->getRepository(Comment::class)->findLast(10);
        return $this->render('traobject/show.html.twig', [
            'traobject' => $traobject,
            'comments' => $comments
        ]);
    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/lost", name="traobjects_lost")
     */
    public function showLost(){
        $stateLost = $this->getDoctrine()->getRepository(State::class)->findOneBy(["label" => State::LOST]);
        $traobjects = $this->getDoctrine()->getRepository(Traobject::class)->findLastTraobjectBy(4, null, $stateLost);
        return $this->render('traobject/lost.html.twig', [
            'traobjects' => $traobjects
        ]);
    }
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/found", name="traobjects_found")
     */
    public function showFound(){
        $stateFound = $this->getDoctrine()->getRepository(State::class)->findOneBy(["label" => State::FOUND]);
        $traobjects = $this->getDoctrine()->getRepository(Traobject::class)->findLastTraobjectBy(4, null, $stateFound);
        return $this->render('traobject/found.html.twig', [
            'traobjects' => $traobjects
        ]);
    }
    /**
     * @Route("/new", name="traobject_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $traobject = new traobject();
        $form = $this->createForm(TraobjectType::class, $traobject);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $file */
            $file = $traobject->getPicture();

            if(!$file){

            }else{
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();


            // Move the file to the directory where brochures are stored
            try {
                $file->move(
                    $this->getParameter('pictures_directory'),
                    $fileName
                );
            } catch (FileException $e) {
            }

            $traobject->setPicture($fileName);
            }
            $em = $this->getDoctrine()->getManager();
            $traobject->setUser($this->getUser());
            $em->persist($traobject);
            $em->flush();

            return $this->redirectToRoute('homepage');
        }

        return $this->render('traobject/new.html.twig', [
            'traobject' => $traobject,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
